name: Portfolio CI/CD

on:
  push:
    branches:
      - main  # Change if you want a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Vite app
      - name: Build project
        run: npm run build

      # 5. Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v22
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}      # sometimes called org id
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: true   # true = production, false = preview
